{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pizzas sold/failed per min",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(pizzas_sold{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "sold"
    },
    {
     "expr": "rate(pizzas_failed{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "users_active{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service-dev\", method=\"all\"}[1m])",
     "legendFormat": "all"
    },
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service-dev\", method=\"delete\"}[1m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service-dev\", method=\"get\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service-dev\", method=\"post\"}[1m])",
     "legendFormat": "post"
    },
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service-dev\", method=\"put\"}[1m])",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "auth_success{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "success"
    },
    {
     "expr": "auth_failed{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "pizzas_latency{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Pizza Latency"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "service_latency{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "CPU and Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "memory_usage{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Pizza Revenue",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizzas_revenue{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}